### ISSUE TITLE
Duplicated pages when reaching FriendFeed old entries limit

### ISSUE THREAD

**Issue by osiride** [claudioc/ffexp#4]
A well known limitation of FriendFeed is that you cannot access old entries. When this limit is reached, ffexp continues to append the last page over and over instead of stopping.

Reproducible by attempting to export a large feed, eg filter/discussions or a large group.

**Comment by zoblue** [comment]
This has happened to me as well. I did not realize the script was looping until the next day when the command window showed a lot of skipped images. My exported html file has a lot of repeated content at the end.

**Comment by claudioc** [comment]
mmh... I guess it would be possible to know after which page you start getting the repeated content... if it is the case, one could try setting the `$max_pages` value on the top of the script to a value which is -1 the maximum?

**Comment by claudioc** [comment]
I updated the script with a more robust error check. I didn't try it against a big stream, though. Can you try again? Thanks.

**Comment by osiride** [comment]
Unfortunately, it didn't solve this issue.

Il giorno gio 12 mar 2015 00:36 Claudio Cicali <notifications@github.com>
ha scritto:

**Comment by claudioc** [comment]
OK, the new version should have this problem fixed.

**Comment by osiride** [comment]
It does seem so, thanks.

Il giorno gio 12 mar 2015 14:02 Claudio Cicali <notifications@github.com>
ha scritto:
